## 🧬 Embedding layer

- A simple lookup table
- Can be trained, but once trained, it is fixed.
- Simply maps each word(or index) to a vector of real numbers.

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

---

In [2]:
word_to_ix = {"hello": 0, "world": 1}
# embedding is initialized randomly and is learned
embeds = nn.Embedding(2, 5)  # 2 words in vocab, 5 dimensional embeddings
lookup_tensor = torch.tensor([word_to_ix["hello"]], dtype=torch.long)
print(f"{lookup_tensor=}")

lookup_tensor=tensor([0])


In [3]:
hello_embed = embeds(lookup_tensor)
print(hello_embed)

tensor([[ 0.6614,  0.2669,  0.0617,  0.6213, -0.4519]],
       grad_fn=<EmbeddingBackward0>)


---

## 🏋🏻 Get Weights of Embedding layer

- But, initially, the weights are randomly initialized.

In [4]:
embeds.weight

Parameter containing:
tensor([[ 0.6614,  0.2669,  0.0617,  0.6213, -0.4519],
        [-0.1661, -1.5228,  0.3817, -1.0276, -0.5631]], requires_grad=True)

In [5]:
lookup_tensor = torch.tensor([word_to_ix["world"], word_to_ix["hello"]], dtype=torch.long)
print(f"{lookup_tensor=}")
hello_embed = embeds(lookup_tensor)
print(hello_embed) # this has `grad_fn=<EmbeddingBackward>`, means it's a learnable parameter (back-propagated)

lookup_tensor=tensor([1, 0])
tensor([[-0.1661, -1.5228,  0.3817, -1.0276, -0.5631],
        [ 0.6614,  0.2669,  0.0617,  0.6213, -0.4519]],
       grad_fn=<EmbeddingBackward0>)


---

### ❌ throws error if index is out of range

In [6]:
lookup_tensor = torch.tensor([[4]], dtype=torch.long)
print(f"{lookup_tensor=}")
try:
    hello_embed = embeds(lookup_tensor)
except Exception as e:
    print("Exception: ", e)

lookup_tensor=tensor([[4]])
Exception:  index out of range in self
